version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: gg_user
      POSTGRES_PASSWORD: gg_pass
      POSTGRES_DB: gg_campaigns
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: targeting-api
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  postgres_data:
